kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-hdd
  namespace: mailu-mailserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage
  namespace: mailu-mailserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
